"""initial schema

Revision ID: 8d1c1fc758d5
Revises: 
Create Date: 2026-08-30 14:46:58.824377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1c1fc758d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_metrics',
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_hour', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('attributed_orders', sa.Integer(), nullable=False),
    sa.Column('attributed_gmv', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('reported_roas', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'metric_date', 'metric_hour')
    )
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=96), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('shops',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_shop_id', sa.String(length=64), nullable=False),
    sa.Column('shop_cipher', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_shop_id')
    )
    op.create_table('ad_accounts',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('external_advertiser_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_advertiser_id')
    )
    op.create_table('alerts',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_dedupe_key'), 'alerts', ['dedupe_key'], unique=False)
    op.create_table('analytics_data_quality',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creators',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_creator_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_creator_id')
    )
    op.create_table('integration_sync_state',
    sa.Column('integration', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_successful_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration', 'resource_type', 'shop_id')
    )
    op.create_table('orders',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('buyer_paid_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gross_merchandise_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('seller_discount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('platform_discount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_order_id')
    )
    op.create_index(op.f('ix_orders_order_created_at'), 'orders', ['order_created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_table('payouts',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_payout_id', sa.String(length=96), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payout_status', sa.String(length=32), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank_reference', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_payout_id')
    )
    op.create_table('products',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_product_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_product_id')
    )
    op.create_table('raw_api_responses',
    sa.Column('integration', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('request_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_resource_fetched', 'raw_api_responses', ['integration', 'resource', 'fetched_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('estimated_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_settlement_id', sa.String(length=96), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('settlement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_settlement_id')
    )
    op.create_table('shop_config',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('minimum_net_margin', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('minimum_profit_per_order', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('max_acceptable_cpa', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('minimum_sample_impressions', sa.Integer(), nullable=False),
    sa.Column('minimum_sample_clicks', sa.Integer(), nullable=False),
    sa.Column('minimum_sample_orders', sa.Integer(), nullable=False),
    sa.Column('alert_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('report_time_local', sa.String(length=5), nullable=False),
    sa.Column('operating_mode', sa.String(length=32), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_table('analytics_order_profit',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('profit_status', sa.String(length=16), nullable=False),
    sa.Column('sale_proceeds', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('seller_discounts', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('platform_fees', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('affiliate_commission', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('seller_shipping', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('refunds', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('subsidies', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('adjustments', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('net_seller_revenue', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('packaging', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('inbound_logistics', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('other_variable', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('contribution_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('allocated_ad_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('attribution_method', sa.String(length=32), nullable=False),
    sa.Column('attribution_confidence', sa.String(length=8), nullable=False),
    sa.Column('estimated_net_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_order_profit_order_id'), 'analytics_order_profit', ['order_id'], unique=False)
    op.create_index('ix_order_profit_current', 'analytics_order_profit', ['order_id', 'is_current'], unique=False)
    op.create_table('analytics_reconciliation',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('difference', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_reconciliation_order_id'), 'analytics_reconciliation', ['order_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('ad_account_id', sa.BigInteger(), nullable=False),
    sa.Column('external_campaign_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('objective', sa.String(length=64), nullable=True),
    sa.Column('campaign_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('budget', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('budget_mode', sa.String(length=32), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_account_id', 'external_campaign_id')
    )
    op.create_table('creator_metrics',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('videos_count', sa.Integer(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('gmv', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('estimated_profit', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'metric_date')
    )
    op.create_table('skus',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('external_sku_id', sa.String(length=64), nullable=False),
    sa.Column('seller_sku', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('variation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'external_sku_id')
    )
    op.create_index(op.f('ix_skus_seller_sku'), 'skus', ['seller_sku'], unique=False)
    op.create_table('tasks',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('expected_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_entity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('baseline_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_video_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('video_reference', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_video_id')
    )
    op.create_table('ad_groups',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('external_adgroup_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('budget', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('optimization_goal', sa.String(length=64), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'external_adgroup_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('external_item_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_list_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit_sale_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gross_item_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('discounts', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('source_video_id', sa.BigInteger(), nullable=True),
    sa.Column('attribution_source', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku_id'), 'order_items', ['sku_id'], unique=False)
    op.create_table('product_metrics',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('gmv', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('refunds', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sku_id', 'metric_date')
    )
    op.create_table('sku_cost_versions',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('cogs_per_unit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('packaging_per_unit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('inbound_logistics_per_unit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('other_variable_cost_per_unit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_sku_from', 'sku_cost_versions', ['sku_id', 'effective_from'], unique=False)
    op.create_table('video_metrics',
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_hour', sa.Integer(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('product_clicks', sa.BigInteger(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('gmv', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gpm', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'metric_date', 'metric_hour')
    )
    op.create_table('ads',
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('external_ad_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_group_id', 'external_ad_id')
    )
    op.create_table('finance_transactions',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=96), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=True),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('native_type', sa.String(length=96), nullable=False),
    sa.Column('normalized_type', sa.String(length=48), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settlement_id', sa.BigInteger(), nullable=True),
    sa.Column('payout_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('raw_response_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_api_responses.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_transaction_id')
    )
    op.create_index(op.f('ix_finance_transactions_external_order_id'), 'finance_transactions', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_transaction_at'), 'finance_transactions', ['transaction_at'], unique=False)
    op.create_table('ad_creatives',
    sa.Column('ad_id', sa.BigInteger(), nullable=True),
    sa.Column('external_creative_id', sa.String(length=64), nullable=False),
    sa.Column('external_video_id', sa.String(length=64), nullable=True),
    sa.Column('creative_type', sa.String(length=32), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_creative_id')
    )
    op.create_index(op.f('ix_ad_creatives_external_video_id'), 'ad_creatives', ['external_video_id'], unique=False)
    op.create_table('creative_mappings',
    sa.Column('ad_creative_id', sa.BigInteger(), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('mapping_source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_creative_id'], ['ad_creatives.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_creative_id', 'video_id', 'product_id', 'sku_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creative_mappings')
    op.drop_index(op.f('ix_ad_creatives_external_video_id'), table_name='ad_creatives')
    op.drop_table('ad_creatives')
    op.drop_index(op.f('ix_finance_transactions_transaction_at'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_external_order_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_table('ads')
    op.drop_table('video_metrics')
    op.drop_index('ix_cost_sku_from', table_name='sku_cost_versions')
    op.drop_table('sku_cost_versions')
    op.drop_table('product_metrics')
    op.drop_index(op.f('ix_order_items_sku_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('ad_groups')
    op.drop_table('videos')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_skus_seller_sku'), table_name='skus')
    op.drop_table('skus')
    op.drop_table('creator_metrics')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_analytics_reconciliation_order_id'), table_name='analytics_reconciliation')
    op.drop_table('analytics_reconciliation')
    op.drop_index('ix_order_profit_current', table_name='analytics_order_profit')
    op.drop_index(op.f('ix_analytics_order_profit_order_id'), table_name='analytics_order_profit')
    op.drop_table('analytics_order_profit')
    op.drop_table('shop_config')
    op.drop_table('settlements')
    op.drop_table('recommendations')
    op.drop_index('ix_raw_resource_fetched', table_name='raw_api_responses')
    op.drop_table('raw_api_responses')
    op.drop_table('products')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('integration_sync_state')
    op.drop_table('creators')
    op.drop_table('analytics_data_quality')
    op.drop_index(op.f('ix_alerts_dedupe_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('ad_accounts')
    op.drop_table('shops')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('ad_metrics')
    # ### end Alembic commands ###
